    DROP TABLE IF EXISTS USER;
    DROP SEQUENCE IF EXISTS USER_SEQ;

    create table USER (
        IDX BIGINT PRIMARY KEY,
        NAME VARCHAR(50) not null,
        PASSWORD VARCHAR(24) not null,
        REG_NO VARCHAR(24) UNIQUE not null,
        USER_ID VARCHAR(50) UNIQUE not null
    );
    CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;

    DROP TABLE IF EXISTS SCRAP001;

    create table SCRAP001 (
        IDX BIGINT PRIMARY KEY,
        INCOME_TYPE VARCHAR(50) NOT NULL,
        TOTAL_PAY BIGINT NOT NULL,
        JOB_START_DAY VARCHAR(10) NOT NULL,
        COMPANY VARCHAR(50) NOT NULL,
        NAME VARCHAR(50) NOT NULL,
        REG_NO VARCHAR(24) UNIQUE not null,
        PAY_DATE VARCHAR(10) NOT NULL,
        JOB_END_DAY VARCHAR(10),
        INCOME_CLASS VARCHAR(50) NOT NULL,
        SERVICE_NUM VARCHAR(20) NOT NULL
    );

    DROP TABLE IF EXISTS SCRAP002;

    create table SCRAP002 (
        IDX BIGINT PRIMARY KEY,
        INCOME_CLASS VARCHAR(50) NOT NULL,
        TOTAL_AMOUNT BIGINT NOT NULL
    );